#cloud-config

hostname: CoreOS

coreos:
  etcd:
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

users:
  - name: core
    passwd: $1$/KzkEYBe$W.HyrB9TuP5stVbMatf/6.
    groups:
      - sudo
      - docker